bug (video dataloader): We aren't doing multi-GPU for testing purposes so we have
```
ValueError: prefetch_factor option could only be specified in multiprocessing.let num_workers > 0 to enable multiprocessing, otherwise set prefetch_factor to None.
```
as an error to be fixed